### ISSUE TITLE
Where do we store portal state

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/xdg-desktop-portal#10]
The designers favor an approach where we show the annoying dialog a few times, and if the user makes the same choice a few times, we just go ahead and do it automatically from there on. I think we already do something like that for geolocation.

For open uri, that would imply that we a table of

requesting app + content-type -> chosen app + count

In addition, we need a way to let users set a threshold value for the count, including a way to say "always ask".

**Comment by alexlarsson** [comment]
Flatpak has something called the permission store which can be used for this. It stores the document db, as well as the geoclue db for the shell.

**Comment by mariospr** [comment]
I've been looking into using the PermissionStore for storing the information needed for the OpenURI portal right now, but I'm a bit confused on how the Permission Store could be used for that case since it seems to aimed at the use case of the documents portals, but does not seem to fit rightaway (at least "semantically", if that makes any sense) for other, more generic cases.

I've checked https://github.com/GNOME/gnome-shell/blob/master/js/ui/status/location.js#L375 for the particular case and my impression is that the shell is using this permissions-related store as a generic database to store permissions-unrelated stuff, so I think I could do that for the purpose of the OpenURI portal, but I'd like a confirmation / correction on whether that's the right approach, if possible.

**Comment by matthiasclasen** [comment]
Yes, we would use the permission store in a way that is not related to storing permissions, at least not directly: It is more like storing history of past interactions, and the desktop portal will derive decisions about the current interaction from it. Maybe we should be renaming it to something more neutral.

**Comment by mariospr** [comment]
Thanks @matthiasclasen for the clarifications, it makes sense now. I'll continue using the permissions store as it is now, since the 'permissions' concept seems to be very deep inside flatpak and I rather not mess with that for now, if that's ok.

**Comment by alexlarsson** [comment]
Well, the history is what makes it a permission in this usecase.
Anyway, the permission portal is pretty freeform in what you store in it. You either pick a uniqe table name for your use and go wild with how you use the id, data and the permission strings. Or you can share a table between multiple users. For instance, one can share a  permission by using a shared table with the id being the thing your're controlling permission to, say "geo-location" and the permissions being "exact", "fuzzy", etc. That way other users can reuse the table for things other than geo-location.

In fact, this is how gnome-shell uses it for geoclue, and we should share that table if we have a similar layout. I think its called "desktop" or something.

**Comment by mariospr** [comment]
I see. At the moment what I'm doing is simply using the Set/Lookup functions and storing the relevant information related to the latest used app for a content type in the "data". The table name I'm using is called (for now) "desktop-used-apps" and at the moment this is the data is storing, as checked using d-feet:
```
'org.mariospr.FlatpakTest:x-scheme-handler/http' -> (@a{sas} {}, <('epiphany.desktop', uint32 5)>)
```
I constructed the key as "<requesting app>:<content type>" and I'm at the moment using that information in the frontend to detect when an app has been used consecutively for a few times (I'm hardcoding 5 as a threshold for now), in which case I add an extra option `use-first-choice` to hint the backend into using the first choice from the list and forget about the dialog.

Does that sound as something reasonable?

**Comment by alexlarsson** [comment]
Its kinda weird, the overall idea is that you name the things you want to give permissions to, which is the "id", like a database key. Then you can add global data to it (in e.g. the document portal the id is the hex key, and the data is the pathname), and per-app arrays of permissions. This is mirrored in the api in that you can SetPermission which modifies a single apps permission, leaving the others in place.

On the other hand, your usecase is a bit different. Maybe that mapping is fine.

**Comment by mariospr** [comment]
Yes, it's weird indeed. That's why I initially thought that the permissions store API was a bit strange for this use case, which is why I ended up treating it like a generic database, at least for now

**Comment by alexlarsson** [comment]
Another alternative is to use
id=x-scheme-handler/http (or just http)
permissions = [ "org.mariospr.FlatpakTest", [ "epiphany.desktop:5"] ]
data = {}

Seems a bit closer to what the idea behind the db was.

**Comment by mariospr** [comment]
As mentioned on IRC, I just saw this comment now so I pushed my branches anyway for now to at least get some feedback. I'll come back after dinner and work on migrating to using the permissions field instead the 'data' one, if that's a better fit.

Btw, about the id... is there any reason why you don't want to include the originating flatpak-ed app's ID as part of it? I think it would be a good idea so that the preferences are not shared by different sandboxed apps, but perhaps I'm missing something?

**Comment by mariospr** [comment]
Non sense, it seems that the brexit thing had my head malfunctioning yesterday, because I know see you were already suggesting to include the name of the requesting application, only that not as part of the id, but as the 'app' field when using the SetPermission API.

Actually this help me clarify the difference between the Set and SetPermission methods, so it's all clear now. Sorry for the noise

**Comment by mariospr** [comment]
Just updated the two PRs. Let me know what you think, thanks!

**Comment by matthiasclasen** [comment]
I've merged the xdg-desktop-portal one, thanks!

**Comment by mariospr** [comment]
Thanks, the other branch is ready to be re-reviewed now too.
