### ISSUE TITLE
Arbitrary host command portal

### ISSUE THREAD

**Issue by orowith2os** [flatpak/xdg-desktop-portal#1003]
Flatpak provides flatpak-spawn as a sandbox escape, which is utilized when an application needs to do something that the sandbox can't provide (at all, or yet). This currently requires *full* access to the appropriate dbus name.

A new, more limited, version of this portal could allow apps to *request* the ability to run commands on the host, so the sandbox escape would be more interactive. 

An app would be able to list the binaries it needs to run, ideally with all the arguments in a one-time escape, and the user would allow this through. 

In the ideal situation, a portal specifically for the tasks needed would be implemented, but there's no way to cover *all* use cases just yet, or nobody is willing to develop the portals needed.

**Comment by orowith2os** [comment]
Some examples of apps that could utilize this are Steam and Lutris (and other game managers), or applications that need a bit of setup on the host side.

**Comment by Mikenux** [comment]
> but there's no way to cover _all_ use cases just yet

To cover the cases, they must be known. You mention two apps, but not everyone uses them. "applications that need a bit of setup on the host side." is vague, so people should see what it means by testing the app or looking at their code.

> or nobody is willing to develop the portals needed.
To do that, they have to find a solution, that solution has to be approved, then development can happen (plus possibly develop what isn't already implemented in flatpak), and there's also the UI (mockups + development).

This also applies to the portal you want. The first thing is to know what to ask the user, knowing that it cannot be vague, which is the problem here. You have to know how to ask for it, what to present, but that would certainly involve neglecting the naive user.

> This could also obsolete some other portal requests.

Which?

**Comment by orowith2os** [comment]
Thinking about this again, it's kind of useless. It's hard to manage, and flatpak-spawn already exists.
