### ISSUE TITLE
Settings portals should not be provided unconditionally

### ISSUE THREAD

**Issue by kennylevinsen** [flatpak/xdg-desktop-portal#1017]
With the new portal configuration, we can finally set per-desktop environment behavior, avoiding situations where e.g. xdg-desktop-portal-gnome is attempted called if it is installed, despite only working under GNOME.

The settings portal unfortunately disregards this, always providing all available backends at once (013c117a545cbc280ad0e0bc3f3184bebff80d45). This means that the GNOME portal may still be attempted activated outside of GNOME, which usually just leads to hangs until the service activation times out.

I believe the preferable solution would be to also respect the portal configuration, adjusting find_all_portal_implementations to return all implementations specified, rather than all implementations available.

**Comment by matthiasclasen** [comment]
That is very much intentional, the idea is that you want settings to be merged, since there are desktop-specific settings in these portals. Why should a kde application miss its kde-specific settings, just because it runs under gnome?

**Comment by jadahl** [comment]
> which usually just leads to hangs until the service activation times out

This should be fixed now.

> That is very much intentional, the idea is that you want settings to be merged, since there are desktop-specific settings in these portals.

If you want settings from `xdg-desktop-portal-gnome` but running outside of GNOME, it needs to run in a special "headless" mode where it doesn't try to be an actual fully fledged portal backend. We could I guess in theory detect this ourselves over in xdp-gnome and be settings only automatically.

**Comment by kennylevinsen** [comment]
Hmm, discussion is going to be duplicated slightly between the PR and the issue.

> That is very much intentional, the idea is that you want settings to be merged, since there are desktop-specific settings in these portals. Why should a kde application miss its kde-specific settings, just because it runs under gnome?

Support for that should be maintained, but a user or DE might also want to instead pick which backends to use and what ordering they should have, should they so desire.

As an example, I might want to use Darkman (providing automatic dark-mode color-scheme changes) under sway, but let GNOME manage things on its own there without accidentally conflicting with the GNOME Settings interactions. Likewise, I may *not* want KDE or GNOME settings made available under another environment, having an alternate provider with more DE-appropriate settings instead.

I imagine such cases will only grow more common, and under the new system we can have our cake and eat it too.

**Comment by WhyNotHugo** [comment]
> Why should a kde application miss its kde-specific settings, just because it runs under gnome?

The current behaviour is weird to be honest. If I want to run a KDE application on non-KDE an I expected to run the xdp-kde on my host? Or, in order to run a gtk application on a non-gtk desktop, I need to install the xdp-gtk too?

I understand that one of the goals of Flatpak is to bundle all application dependencies. But the current behaviour goes completely against these expectations, requiring users to both install and run per-toolkit portals on their host.

I think that keeping the current behaviour doesn't provide incentives to fix this issue. Quite the contrary, it provides a clear path for the next toolkit to also say "you need our settings portal on the host for our applications to work properly".

**Comment by matthiasclasen** [comment]
> The current behaviour is weird to be honest. If I want to run a KDE application on non-KDE an I expected to run the xdp-kde on my host? Or, in order to run a gtk application on a non-gtk desktop, I need to install the xdp-gtk too?

You aren't expected to do anything. If the kde portal backends are installed on the host, the setttings portal frontend will consult them to make kde-specific settings available.

> I think that keeping the current behaviour doesn't provide incentives to fix this issue. Quite the contrary, it provides a clear path for the next toolkit to also say "you need our settings portal on the host for our applications to work properly".

Desktop-specific settings are a reality. If we ignore them, we will get complaints too.

**Comment by ebassi** [comment]
The main issue is that even when disabling all portals, xdg-desktop-portal will still try to activate all implementations because we have portals that bypass the configuration file. This adds unnecessary complexity to portal implementations, which have to handle "adversarial" conditions like being activated in a different session; to xdg-desktop-portal, which has to bypass configuration for specific portals; and to OS integrators, who would actually use the configuration file but can't, and currently have to resort to clobbering the environment to avoid starting all portals.

If your environment is using the GNOME settings, then you should explicitly add the settings portal to your configuration.

**Comment by Rongronggg9** [comment]
#1018, plus https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/commit/a877a89b8636cabcd8c341eca17aa68e5f6eb5b7, actually broke something:
1. GTK backend is not provided
2. GTK programs then unable to read `org.gnome.desktop.interface` namespace, especially `gtk-theme` and `icon-theme` keys, which provide the current KDE theme if properly configured
3. As a result, if those GTK programs that read theme via portal (e.g. if `GTK_USE_PORTAL=1` is set in the environment) don't attempt to get the current theme in other methods, they have to fall back to, for example, the Adwaita theme

x-d-g-kde <5.27.8 which does not ship `kde-protals.conf` (making x-d-g work in fallback mode). The Settings portal will not be available in this case, but those GTK programs seem to work fine.

**Comment by ebassi** [comment]
> #1018, plus https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/commit/a877a89b8636cabcd8c341eca17aa68e5f6eb5b7, actually broke something:
> 
>     1. x-d-p-gtk backend is not provided

If your session depends on providing GNOME settings to GTK applications, then you'll have to make this dependency explicit.

>     2. GTK programs then unable to read `org.gnome.desktop.interface` namespace, especially `gtk-theme` and `icon-theme` keys, which provide the current KDE theme if properly configured

GTK programs using Wayland can directly access the GSettings storage without going through the portal. If they go through the portal then something has to be able to deal with that.

>     3. As a result, if those GTK programs that read theme via portal (e.g. if `GTK_USE_PORTAL=1` is set in the environment) don't attempt to get the current theme in other methods, they have to fall back to, for example, the Adwaita theme

Don't use `GTK_USE_PORTAL` to "force" behavioural changes: it's not a configuration mechanism, it's a debugging utility. That's why GTK4 renamed the environment variable, to make this even more clear and avoid people getting tricked by poor decisions made by wiki contributors.

> x-d-p-kde <5.27.8 which does not ship `kde-protals.conf` (making x-d-p work in fallback mode). The Settings portal will not be available in this case, but those GTK programs seem to work fine.

"Fallback mode" means the `UseIn` key; is the KDE portal setting that to `KDE;gtk;`? That's the only way it'd work.

> The potential fix may be:
> 
>     1. x-d-p-kde ships `kde-protals.conf` with `org.freedesktop.impl.portal.Settings=kde;gtk`. However, it will make x-d-p-kde somewhat "depends" on x-d-p-gtk, at least in the sight of distributions, which is kind of weird.

The GTK portal implementation should really be renamed "FDO": it's considered a "portal of last resort", so it's not entirely weird to have it: https://github.com/flatpak/xdg-desktop-portal/issues/1077

The gtk portal recently dropped all the optional support for private GNOME interfaces: https://github.com/flatpak/xdg-desktop-portal-gtk/pull/438

>     3. x-d-p hardcodes x-d-p-gtk as a fallback if the currently selected backend does not provide the queried namespace.

See https://github.com/flatpak/xdg-desktop-portal/issues/1077#issuecomment-1691727273

Another option is to stop trying to make GTK applications look like KDE ones; I know that it can be quite a challenge when it comes to appearances, but I can guarantee that very, very few people even test GTK/GNOME applications with KDE styling, so things have a tendency to break.

**Comment by smcv** [comment]
@Rongronggg9:
> actually broke something

If you think xdg-desktop-portal is (now) doing something wrong, please could you open a new issue, rather than replying to a closed one?

**Comment by smcv** [comment]
> The gtk portal recently dropped all the optional support for private GNOME interfaces

Most, rather than all. There are still GNOME-specific implementations of Wallpaper (compile-time optional, duplicated in xdp-gnome) and Lockdown (compile-time optional, duplicated in xdp-gnome). Also, the Inhibit implementation still has code paths for org.gnome.SessionManager/org.gnome.ScreenSaver (which are not duplicated in xdp-gnome).

**Comment by smcv** [comment]
> x-d-p-kde [could ship kde-portals.conf] with org.freedesktop.impl.portal.Settings=kde;gtk. However, it will make x-d-p-kde somewhat "depends" on x-d-p-gtk, at least in the sight of distributions, which is kind of weird.

If this is what KDE wants, then the only way to achieve that is to ask for it, by saying so in kde-portals.conf and in packaging; or if KDE doesn't want this strongly enough to ask for it, then nothing is going to guarantee that xdp-gtk gets installed or used.

Perhaps xdp-kde should be a strong dependency for Plasma Desktop, for example `Depends` or `Recommends` in Debian, but xdp-gtk should be a weaker (optional) dependency, perhaps `Recommends` or `Suggests`?

If I understand correctly, it's fine to list backends in `foo-portals.conf` that are not installed: they just won't be used.

**Comment by kennylevinsen** [comment]
It should also be noted that "iface=kde;gtk" is not a hard dependency, and that "iface=*" is also an option.

There might be an issue with fallback when there is no configuration at all (the settings portal uses a different path without any fallback logic), but indeed please open a new issue. Sharing the verbose output from a run of xdg-desktop-portal with and without the kde config installed would also be useful.

**Comment by nicolasfella** [comment]
With my KDE hat on I find myself confused about what is expected from Plasma/x-d-p-kde here.

> If this is what KDE wants

What I want is for GTK apps to work properly. (I'm not even talking about following KDE theming or anything, just basic things like fonts not looking awful). Apparently that requires x-d-p-gtk to be present. 

I want this to work out of the box without Plasma doing anything special to accomodate for GTK.

> x-d-p-kde ships kde-protals.conf with org.freedesktop.impl.portal.Settings=kde;gtk

I don't see why Plasma should do that, given the dependency on x-d-p-gtk comes from GTK applications, not Plasma

**Comment by kennylevinsen** [comment]
For the Settings interface specifically,  I opened https://github.com/flatpak/xdg-desktop-portal/pull/1106 to restore the old "use by default" behavior of the Settings portal, resolving the particular follow-up issue.

For *all other interfaces*, the active portal configuration (provided by the user, by KDE, or something else) must specify which portal to use - including fallback to e.g. Gtk if there is something the KDE portal does not implement that a Gtk application might need.

**Comment by travier** [comment]
We are impacted by this change in Fedora 39: https://pagure.io/fedora-kde/SIG/issue/396. Reverting to `xdg-desktop-portal-1.17.0-3.fc39.x86_64` "solves" this issue.

I've tried to understand what the KDE portal should do here but I don't understand which configuration file we're supposed to ship and how that would help.

**Comment by travier** [comment]
Might be as well: https://bugs.kde.org/show_bug.cgi?id=474746

The following appear to solve the situation:
```
$ cat /usr/share/xdg-desktop-portal/kde-portals.conf
[preferred]
default=kde;gtk
```

**Comment by smcv** [comment]
A less brute-force version of the previous comment would be:

```
[preferred]
default=kde;
org.freedesktop.impl.portal.Settings=kde;gtk;
```

**Comment by smcv** [comment]
As I previously said, if you think xdg-desktop-portal is (now) doing something wrong, please open a new issue, rather than replying to a closed one. I am trying to be helpful (I didn't design this change!) but there is a limit to my patience for having design discussions in comments on a closed issue.

> What I want is for GTK apps to work properly. (I'm not even talking about following KDE theming or anything, just basic things like fonts not looking awful). Apparently that requires x-d-p-gtk to be present.

If your objection is to the defaults that are hard-coded into GTK to be used in the absence of any particular configuration, then upgrading any GTK apps to a runtime that contains GTK 3.24.29 or later, or 4.2.1 or later, should hopefully help that (for [gtk!3406](https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/3406) and [gtk!3409](https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/3409), or their GTK 4 equivalents). Or, if those changes weren't sufficient to make the defaults meet your expectations, then that would be a GTK bug/feature-request, in which case please open a new GTK issue. (Of course, if the apps are using an EOL runtime, they aren't going to get a newer GTK, however much newer upstream releases of GTK might get fixed; but improving GTK's defaults benefits everyone in the long run.)

Or, if you want something other than GTK's defaults - in other words, you want GTK's defaults to be overridden by something - then there needs to be something in the overall system that tells GTK apps what non-default setting to use. Either it can be x-d-p-gtk, or x-d-p-kde could translate KDE settings into the closest equivalents that will be used by GTK, or x-d-p-kde could say that it knows best and force values for the relevant keys. It's up to the maintainer of x-d-p-kde, and/or the maintainer of whatever package ships `kde-portals.conf` (which at the moment is *also* x-d-p-kde).

Recent versions of xdg-desktop-portal put the choice of portal backend under the desktop environment's control: this gives the desktop environment power, but also responsibility. I'm sorry, but "I want GTK to have settings of my choice" and "I don't want GTK-specific code anywhere in the overall system" are not compatible: if its defaults are not acceptable to you, then *something* has to tell it to behave differently.

The point of #1018, other than giving desktop environments that control, was to resolve the problem described in https://github.com/flatpak/xdg-desktop-portal/issues/1017#issuecomment-1633972386.
