### ISSUE TITLE
Automate releases using GitHub Actions

### ISSUE THREAD

**Issue by GeorgesStavracas** [flatpak/xdg-desktop-portal#1090]
Currently there still is a fair amount of manual work to do in order to get a release out. It's documented in the [RELEASE_HOWTO.md file](https://github.com/flatpak/xdg-desktop-portal/blob/main/RELEASE_HOWTO.md). Ideally, the most of the release process would be automated, necessitating only a tag to kick off a full release.

To do this, we need to satisfy some preconditions:

 * The `main` branch must always correctly run `meson dist` (https://github.com/flatpak/xdg-desktop-portal/pull/1089)
 * Translations should be generated automatically (when? how?)
 * Force-pushing to `main` must be entirely blocked - even for maintainers

**Comment by whot** [comment]
fwiw, [input-wacom](https://github.com/linuxwacom/input-wacom/blob/master/.github/workflows/tagged-release.yml) recently switched to doing that, in case you need an example to get ideas from.

**Comment by flexagoon** [comment]
I did some experimentation and yes, it is absolutely possible to run an action when a tag is pushed and then add a commit to that existing tag.

So the choice is probably between three workflows:

1. Generating translations after every pr, as outlined in my previous comment
2. Generating and force-pushing translations when a new tag is added
3. Instead of adding any tags, the maintainers manually trigger the "release" github action, which commits updated translations and then that action creates the tag

Which of those would be preferred?

**Comment by flexagoon** [comment]
Hmm, I don't think there is any way to interactively provide inputs to a GitHub action.

Perhaps there could be a releases.yaml/toml/json/whatever file that triggers a release when someone commits to it?

**Comment by flexagoon** [comment]
Oh, wait, you can actually provide inputs to an action:

https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

However, you can't provide a multiline string to it

https://github.com/orgs/community/discussions/12882

So I'm not sure if it'll be a good fit for changelogs.

**Comment by GeorgesStavracas** [comment]
Nah, it's fine to update the NEWS file before running the action :)

**Comment by flexagoon** [comment]
Oops, I didn't see that the repo already has a NEWS file.

I'll try to work on this issue then!

**Comment by flexagoon** [comment]
The RELEASE_HOWTO file mentions building the documentation (although it lists the old docbook meson flag instead of the new one). Is this step still necessary or does the `pages.yml` action already handle this?

**Comment by GeorgesStavracas** [comment]
I think that's outdated, `pages.yml` takes care of that already.

**Comment by flexagoon** [comment]
@GeorgesStavracas another question:

The version and the changelog can be taken from the NEWS file automatically. Should I also use it to automatically determine if the release is a pre-release? (Since this project uses odd numbers in minor versions to denote pre-releases)

**Comment by GeorgesStavracas** [comment]
I think I'd prefer if the version and pre-release checks were manual. I've made mistakes in the NEWS file in the past, it would be disappointing if that ends up messing up releases if it ever happens again.

Not sure if that's possible, but it would be great if the action could check if the release version is strictly bigger than the previous release of the branch. So e.g. on the `main` branch, it'd check for the previous stable or unstable tag, but on a stable branch, it would look for the last stable tag of that version. Not a blocker though!

(I'm very hype about this! Looking forward to see what you're cooking up there.)

**Comment by flexagoon** [comment]
Alright, I'll probably make it so that those values are automatically determined by default but you can also specify them when running the action to override the default values.

At this point I managed to automate most of the release process, but I'm not sure what to do with the SECURITY file and the bug report template. It seems like updating them requires the knowledge of what versions are no longer supported. Is this something that can be automatically determined or should I leave those files to be updated manually?

**Comment by GeorgesStavracas** [comment]
Let's limit the scope for just generating the release for now. Updating the SECURITY file is such a minuscule effort that it can be automated later, if necessary.

I also just thought of something: do you think it would be possible to add a "Dry run" option to the action that runs the the action but doesn't actually do anything, and just *prints* what it was going to do? [Dry runs](https://en.wikipedia.org/wiki/Dry_run_(testing)) are super useful to make sure things will work ahead of time.

**Comment by flexagoon** [comment]
Sure, that would be possible to add, though I'm not really sure what step of the release process this would be useful for - the compilation of the code is already checked by CI on each commit and the rest is basically just updating some files and creating the release.

The only thing that this can probably be useful for is the NEWS file parsing - I can add a flag that skips all of the other steps and just prints the release information, if you want that

**Comment by GeorgesStavracas** [comment]
Sounds good!

**Comment by flexagoon** [comment]
What about updating the version in the `meson.build` file? I assumed that it has to be updated to the current version, but it seems like it's actually supposed to be set to the *next* version? How is that usually done? And if `meson.build` contains the number of the next version, perhaps it can be used to extract that information more reliably instead of the NEWS file?

**Comment by GeorgesStavracas** [comment]
The version in meson.build is updated manually after the release, I don't think the action will have to do anything with it. At most, if you want to go fancy, the action could check if the action release version is equal to meson release version?

**Comment by flexagoon** [comment]
> At most, if you want to go fancy, the action could check if the action release version is equal to meson release version?

That'll mean that there will be three separate sources to extract the version, which just adds unnecessary complexity, so I probably just won't touch meson.build then.

**Comment by GeorgesStavracas** [comment]
Fixed by https://github.com/flatpak/xdg-desktop-portal/pull/1454
