### ISSUE TITLE
Add a portal for keyring access 

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/xdg-desktop-portal#14]
Not clear what do to about kernel keyring, need to talk to domain experts. We believe that libsecret should use the kernel keyring underneath.

**Comment by matthiasclasen** [comment]
Talking about this with Ray, the suggestion is that we create per-application keyrings and mount them in 'the normal place' inside the sandbox. They could be encrypted with a generated token that we store inside the normal session keyring. flatpak would need to know how to unlock the keyring when it sets up the sandbox. seahorse can already handle multiple keyrings, but it would also need to learn about the tokens to unlock these, since the user won't know them.

The alternative is to use the same (user) password for all these keyrings and unlock them all at login, but then the per-application ones are unlocked unnecessarily ahead of time.

**Comment by matthiasclasen** [comment]
I've asked Stef to chime in here.

**Comment by stefwalter** [comment]
So I'm pretty much of the opinion that we should move away from a central keyring database for sandboxed apps.

I talked about this at GUADEC 2013 where the general plan would be to:

1. Use the kernel keyring as a way for sandboxes to request a session key.
2. The kernel keyring has an upcall mechanism that can call an arbitrary executable when a type of key is requested.
3. A "portal" executable provides a session key to each sandbox via the kernel keyring. It returns the same session key for the same sandbox the second time it's asked.
4.The sandboxed app uses the session key to "lock" password data it stores along with its configuration data.

Here's a talk explaining it. Skip ahead to 0:19:01

https://www.superlectures.com/guadec2013/more-secure-with-less-security

And yes there are cons:

 1. It's harder to back up, than a central keyring database: A: Well a password without the related account/config data is pretty useless IMO. Unless we get into having all of that be centralized, this is a non-issue.
 2. Each sandboxed app has to get this right: A: Use a library that consumes the session key and stores password/account data in the app's data space encrypted with that key.

**Comment by matthiasclasen** [comment]
Didn't mean to close this.

Just so I understand this scheme correctly:

There will only be a single session-wide key that is handed out to all sandboxed applications ? Or should the key be different for each app ? In the former case, why not put it in the kernel session keyring at login and be done with it ? In the latter case, I don't think the request-key mechanism gives us any trusted data to identify the app with. I didn't find a way to get the pid of the requestor. 

We could work around that by setting up the per-sandbox key at sandbox creation time. But then we don't need the upcall mechanism at all - is it important to this scheme that keys only be created on demand ?

**Comment by ueno** [comment]
I was pondering this a bit during the weekend. Although using the kernel keyring sounds like an interesting approach, I am not sure if it is still the right way to go; it is known that it doesn't work well with namespaces (though it provides the equivalent functionality) and some tools already started migrating from it.

As far as I understand, the main objective here is to provide secrets API isolated for each application. Given all the objects are exported on a single bus name, a naive approach would be to export them on a unique bus name per application, something like:

1. add a D-Bus method in org.gnome.keyring.Daemon interface to obtain a new secret service on a unique bus name
2. create a portal that bridges gnome-keyring and flatpak'ed application
3. modify libsecret so that it can obtain the unique bus name through the portal

I have work-in-progress branches for them (not working yet):
https://gitlab.gnome.org/GNOME/gnome-keyring/tree/wip/dueno/secrets-helper
https://github.com/ueno/xdg-desktop-portal/tree/wip/dueno/secrets-helper
https://gitlab.gnome.org/GNOME/libsecret/tree/wip/dueno/flatpak

**Comment by matthiasclasen** [comment]
I think the direction we want to go in is a slightly different scheme:

1. flatpak leaks a per-app secret into the sandbox at setup time
2. libsecret in the sandbox is modified to keep secrets in a local file that is encrypted with the secret
If we want to keep a session-wide management tool like seahorse working, it will need to use some privileged api to obtain per-app keys from flatpak

**Comment by ueno** [comment]
Thank you for the clarification; indeed, that makes more sense, and if we only support per-app secrets through the [simple API](https://developer.gnome.org/libsecret/unstable/libsecret-Password-storage.html) (which most apps are using I believe), the implementation would be fairly straightforward. Let me give it a try.

**Comment by ueno** [comment]
I've filed a MR for libsecret at https://gitlab.gnome.org/GNOME/libsecret/merge_requests/6.
@stefwalter @nielsdg review/suggestions would be appreciated.

**Comment by simo5** [comment]
As the world is moving on to increased use of HW tokens for security, any interface that deal with secrets should deal also with passing through and filtering requests to things like U2F tokens.

We cannot give direct access to such tokens, doing so would allow applications to attack each other "App A can authenticate as App B", so a portal that proxies and validate access to tokens becomes necessary.

This basically means you probably want a socket that crosses the sandbox boundary back to a central keyring with a protocol that allows to expose "HW token services" to applications.

**Comment by ueno** [comment]
HW tokens seem like a bit off-topic here, as we don't have consistent support for them even in host applications. We might eventually need a mock USB device (either emulating through sysfs or gadgetfs) with proper access control.

Back to plain old passwords, I still need general guidance/clarification on the following:
1. What would be the mechanism to supply a master secret to sandboxed apps? Using a Unix socket seems like a reasonable option, while D-Bus method call would also work, given that dbus-proxy has full control of isolation. @alexlarsson do you have any preference?
2. Is it sufficient to store the encrypted file in per-app directory? Simo pointed that it would be useful that multiple versions of an application are able to share the same password set, but I suppose it wouldn't be a big deal, because a user typically have at most two versions of app (i.e., stable and development), and the user of the development version wouldn't mind manually copying the keyring files around.

**Comment by hadess** [comment]
I think those are relevant, from iOS:
https://developer.apple.com/documentation/security/password_autofill/
https://www.igeeksblog.com/how-to-use-password-autofill-for-apps-in-ios-11-on-iphone-ipad/

The idea is that the application doesn't have access to the password store, and would request it from a portal. That portal can then list the relevant passwords, or allow you to find a related password (so you can, for example, autofill your <service> webapp password into a native <service> app.

This could also be the entry point for strong password generation, for new accounts created.

Finally, having the portal be responsible for finding that info, is that you could easily replace the native "seahorse/libsecret" combo with a Keepass store to make it possible to migrate the store.

> I do not want to deral the conversation, however the problem of providing APIs that deal only with passwords is that then applications only provide password based interfaces, and the cycle continues, meanwhile the web is getting APIs to allow webapps to do proper 2fa ...

Are we supposed to know what those APIs already look like? I've never seen 2FA be done on a single machine, and I wouldn't know what the APIs or UIs would look like. Links to prior art from contemporary OSes would be useful.

**Comment by hadess** [comment]
This is an implementer's API. What do the client API and UI look like?

**Comment by simo5** [comment]
But support for things like (soft ?) [H|T]OTP tokens would also be useful.

**Comment by simo5** [comment]
The UI is generally just a simple: "insert your token and press the button" statement, with feedback on whether it worked or not.
The API will depend on how we want to render this, from a portal pov you may want to be able to allow/disallow access to the token and select which token you want to use.

**Comment by hadess** [comment]
> The UI is generally just a simple: "insert your token and press the button" statement, with feedback on whether it worked or not.
> The API will depend on how we want to render this, from a portal pov you may want to be able to allow/disallow access to the token and select which token you want to use.

Looks like it should be its own portal then, as the interaction and the API bear no resemblance to passwords.

**Comment by simo5** [comment]
It deals with authentication which is what passwords are used for, this is why I thought the two should be related, but it doesn't have to be.
