### ISSUE TITLE
[open-uri] Portal dialog does not show up with file-manager when uri is a directory

### ISSUE THREAD

**Issue by uajain** [flatpak/xdg-desktop-portal#143]
Ideally, if uri is a directory, it should open up the portal with files-manager (E.g. nautilus) 
Currently there is no such behaviour.

**Comment by mariospr** [comment]
Unless I'm missing something, this has been added in https://github.com/flatpak/xdg-desktop-portal/commit/8c6c6c2f (you'll need https://github.com/flatpak/xdg-desktop-portal/commit/91c69424 too to prevent a crash, though) in master, and will be included in the next stable release.

Thus, closing this ticket since this is resolved already, but feel free to reopen if I misunderstood the report.
