### ISSUE TITLE
URI opened without user confirmation

### ISSUE THREAD

**Issue by amtlib-dot-dll** [flatpak/xdg-desktop-portal#149]
https://github.com/flatpak/xdg-desktop-portal/blob/77abb1c65a5ab6d7b206929594a99bf6ca8fd941/data/org.freedesktop.portal.OpenURI.xml#L28
This portal is said to be under the control of the user. However, when used inside the sandboxed environment to open an URI, the browser will immediately open without any user confirmation.
* If the opened site is a phishing site, the user's password may be under risk
* If the opened site have known XSS vulnerability, the user's account may be under risk
* If the browser is known to have some vulnerability and the site is malformed, the system may be under risk

**Comment by TingPing** [comment]
I think the web browser was relaxed on this because it is very commonly used and a bit of a poor UX to prompt every time.

Honestly though unless the URL is extremely obviously bad just asking the user won't necessarily prevent any of those attacks mentioned and last I saw the portal prompt doesn't even show the URI (It probably should)?

**Comment by amtlib-dot-dll** [comment]
Yes, but there should be a configurable switch for users who need more security than convenience. There are [examples (in Chinese)](https://zhuanlan.zhihu.com/p/32674524) on Android that use the Open URI feature to earn money 😂 of course not for the user but for the "attacker". On Win10 UWP platform there are such prompts.

**Comment by TingPing** [comment]
I believe it is configurable somewhere but it wasn't an obvious place...

**Comment by amtlib-dot-dll** [comment]
😂 Well, is it configurable NOW or sometime in the FUTURE? If now, I think I may dig into the conf files 😂

**Comment by matthiasclasen** [comment]
mario, we should maybe document how this is written in the permission store.
Although it won't be very useful without a tool

**Comment by matthiasclasen** [comment]
In fact, we currently hardcode skipping the app chooser for http:, https: and for directories.

Mario, we should consider flipping around the logic from:
 if (skip_app_chooser || (!always_ask && (latest_count >= latest_threshold)))
to 
 if (!always_ask && (skip_app_chooser || (latest_count >= latest_threshold))

And then the permission store can be used to override skip_app_chooser, by setting always_ask.

**Comment by mariospr** [comment]
@matthiasclasen: I just saw this thread now, but I completely missed the comment on Jan 29, sorry about that.

I think that makes sense, I'll prepare a patch for that

**Comment by mariospr** [comment]
Actually, I need to think a bit more about this and run some tests, since at the moment `always_ask` will be always `TRUE` unless a threshold has been set in the permission store for a given app (which by default hasn't). So, doing such change means that skipping the appchooser dialog for http/https protocols (when there's only one possible app to handle that request) won't ever work in systems that don't define any threshold, and I'm not sure that's what we want?

I can't do much today, but I'll devote some time this week (tomorrow, probably) to check this properly, propose a solution and document things (as I should have done before already).

**Comment by matthiasclasen** [comment]
lets figure out a way that a) preserves the current behavior and b) lets users override the skip

**Comment by matthiasclasen** [comment]
I've started on documentation here: https://github.com/flatpak/xdg-desktop-portal/wiki/The-Permission-Store

**Comment by mariospr** [comment]
@matthiasclasen With "a bit of a delay" with regard to when I wished I had time to look into it, but I've been working on it today and I think the right condition to use, that (a) preserves the current behaviour and (b) allow users to override the skip (via the permission store, extra tool required), is the following one:
```
  if ((always_ask && skip_app_chooser) || (!always_ask && (latest_count >= latest_threshold)))
```

The problem with the current `(skip_app_chooser || (!always_ask && (latest_count >= latest_threshold)))` condition is that it will always skip the dialog [for HTTP/HTTPS schemas and directories](https://github.com/flatpak/xdg-desktop-portal/blob/master/src/open-uri.c#L401) regardless of whether a threshold is specified in the permission store, making it impossible to make the experience more secure, even if you have a tool to alter the `desktop-used-apps` table in the permission store.

Now, the problem with `(!always_ask && (skip_app_chooser || (latest_count >= latest_threshold))` is that the value of `always_ask` depends directly on whether a threshold is set or not for a given app:
  * `always_ask`: `TRUE` if no threshold is set, `FALSE` otherwise

That means that you won't ever skip the dialog unless a threshold is set. However, no threshold is set by default, meaning that `always_ask` is `TRUE` by default and therefore that the `skip_app_chooser` boolean won't ever be checked by default.... meaning that the current behaviour would not be preserved, since by default we would never be skipping the dialog.

Using the newly proposed the condition makes sure that the current behaviour is preserved by skipping the dialog when possible by default (no threshold => `always_ask == TRUE`), while allowing to override that logic by setting a threshold (that makes `always_ask == FALSE`), in which case you would ignore the "can skip dialog" logic and decide whether to show the app chooser depending by comparing `count` to the threshold set.

@matthiasclasen If you agree with this, I'd prepare a patch and update the documentation accordingly.

**Comment by mariospr** [comment]
PR here: https://github.com/flatpak/xdg-desktop-portal/pull/181

Pending to hear feedback before updating the docs at https://github.com/flatpak/xdg-desktop-portal/wiki/The-Permission-Store

**Comment by mariospr** [comment]
Thanks @matthiasclasen , and sorry again for the huge delay.

Updated documentation in https://github.com/flatpak/xdg-desktop-portal/wiki/The-Permission-Store now the PR has been merged.

**Comment by matthiasclasen** [comment]
I think this is good now, as far as the portal itself is concerned. Next step is to find some place for letting users tweak this.
