### ISSUE TITLE
Add a webcam portal

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/xdg-desktop-portal#38]
See:
https://blogs.gnome.org/uraeus/2015/06/30/introducing-pulse-video/

**Comment by matthiasclasen** [comment]
This should be done similar to the pulseaudio module, by calling out to org.freedesktop.portal.Device, once pinos has access control hooks.

**Comment by muelli** [comment]
what's the rationale for closing? Is it possible to access the webcam now without giving up /dev/?

**Comment by hadess** [comment]
Pipewire support was merged, see above.

**Comment by hadess** [comment]
PulseVideo -> pinos -> Pipewire

**Comment by muelli** [comment]
> Pipewire support was merged, see above.

where exactly can I see anything? I see two referenced issues. The flatpak one (83) is still open and the portal one (18) has been closed without further information.

**Comment by matthiasclasen** [comment]
in git

**Comment by muelli** [comment]
You mean https://github.com/flatpak/xdg-desktop-portal/pull/122/? How do I access a web cam through the new ScreenCast portal?

**Comment by matthiasclasen** [comment]
Some pieces are still missing, e.g. the gtk backend, and the mutter code.
I believe we will eventually have an example application that shows this.

**Comment by jadahl** [comment]
The idea is that the camera devices open pipewire contexts from their own portals. It's not meant to be part of the screen cast portal. They have other kind of requirements, such as hot plugging, switching between front and back and such.

**Comment by jadahl** [comment]
I don't think we should close this issue. Web cam access is different from screen casting. In screen casting we create a PipeWire context that we hand over to sandboxed application where we have isolated a prepared set of stream nodes (the one explicitly shared using the portal UI).

Web cam access is different. For example, a camera portal needs to support hot plugging, it needs to know about camera details (is it front/back/external for example).

The permission system used by the screen cast portal to block access to non-screen-cast streams does not support the web cam way of providing access, as it is completely done during setup, thus doesn't support hot-plugging.

What we probably want is a org.freedesktop.portal.Camera. How exactly the permission and hot plugging should work (should the portal be the one sending hotplug events vs should PipeWire call inte the portal to ask whether a hotplug event should be made visible to some given client)

Paging @wtay for status of a permission system that can support hot plugging.

**Comment by matthiasclasen** [comment]
After talking to Jonas a bit more, this should probably be a separate webcam portal.

**Comment by jadahl** [comment]
What about still photos? Do we want two separate "Camera" vs "Webcam/Video camera" portals, or just go generic enough and add a "Camera" portal that supports video that we eventually can extend to potentially deal with still images in a non-PipeWire way?

**Comment by hadess** [comment]
> What about still photos? Do we want two separate "Camera" vs "Webcam/Video camera" portals, or just go generic enough and add a "Camera" portal that supports video that we eventually can extend to potentially deal with still images in a non-PipeWire way?

Mobile devices have separate permissions for Camera and Photos. Usually, the Camera functionality is for direct access to the camera (the app itself shows the cropping controls, effects, etc.), the Photos functionality offers access to the Photos album (either read-only, or read-write), with the ability to also capture a film/photo to be used at that instant.

I'm guessing this issue is about the Camera/Webcam access itself, whether to eventually capture still or videos. The use case here is live video use (video chat, still/film camera application).

The photos access would probably be done through a separate "Photos" document portal, with a way to select whether the list should be just photos, just videos or both. The use case here is an app that wants an image or video (say, to select an avatar, or upload an image to social media), a sort of file chooser specialised in images.

**Comment by jadahl** [comment]
I'm not talking about looking at taken photos, I'm talking about not limiting ourself to "Webcams" specifically, but Cameras in general, be it the ones connected via USB, front facing ones connected to a laptop panel or tablet/smartphone, or on the back used for video capture and taking still photos. It's mostly a question of how to name things (e.g. lets avoid referring to a "Webcam"), and have in mind that we might want to make room for functionality related to cameras (be it for still or motion picture) in general.

**Comment by hadess** [comment]
> I'm not talking about looking at taken photos, I'm talking about not limiting ourself to "Webcams" specifically, but Cameras in general, be it the ones connected via USB,

Like, a webcam, and/or a DSLR with tethered capture?

> front facing ones connected to a laptop panel or tablet/smartphone,  or on the back used for video capture and taking still photos.

"Cameras" is fine for those.

> It's mostly a question of how to name things (e.g. lets avoid referring to a "Webcam"), and have in mind that we might want to make room for functionality related to cameras (be it for still or motion picture) in general.

Yes, and agreed.

But as you mention, there might be some confusion, later down the line, about cameras for image import, or which "camera" types we're talking about. Might be a good idea to discuss this with designers so that we use terms that are clear for each type of device.

**Comment by jadahl** [comment]
> Like, a webcam, and/or a DSLR with tethered capture?

Not really talking about the DSLR. I suspect those either need to access USB directly or Wifi. I can't imagine we can have a generic "system camera" portal for importing from those?

**Comment by hadess** [comment]
> Not really talking about the DSLR. I suspect those either need to access USB directly or Wifi. I can't imagine we can have a generic "system camera" portal for importing from those?

No, there wouldn't be, but you can see the potential confusion if we were to simply use the word "Cameras". That's why designers need to come in to this discussion.

**Comment by allanday** [comment]
> but you can see the potential confusion if we were to simply use the word "Cameras"

That's true, but I'm not sure how big an issue it is. The concept of "camera" access being about internal cameras has been established by mobile, and for most people all cameras are integrated anyway. I'd probably just use the word "camera".

From a UX perspective, I'd like to see camera permission being global. That is, access would be to all cameras, rather than individual cameras. It would be just too painful to manage permissions on a per-camera basis.

Likewise, it would be good if we could ask the user for camera and microphone access simultaneously, [like this](https://raw.githubusercontent.com/gnome-design-team/gnome-mockups/master/shell/access-control/wires-access-dialogs.png), in order to reduce the number of requests users have to deal with.

**Comment by hadess** [comment]
> That's true, but I'm not sure how big an issue it is. The concept of "camera" access being about internal cameras has been established by mobile, and for most people all cameras are integrated anyway. I'd probably just use the word "camera".

That's going to be interesting once we have portals for importing photos from external cameras, or tethered capture.

**Comment by allanday** [comment]
> importing photos from external cameras, or tethered capture.

I'd probably include tethered capture under the same umbrella as internal webcam access - if I trust an app to use an integrated webcam, I probably trust it to use a USB webcam too.

It's a bit hard to say about importing from an external camera without knowing more about what that will look like. One key question is whether it's possible that the two types of request could be made at the same time - we wouldn't want "Firefox wants to access your cameras" and "Firefox wants to access Sony Camera 12341234" to appear one after the other.

**Comment by hadess** [comment]
> It's a bit hard to say about importing from an external camera without knowing more about what that will look like. One key question is whether it's possible that the two types of request could be made at the same time - we wouldn't want "Firefox wants to access your cameras" and "Firefox wants to access Sony Camera 12341234" to appear one after the other.

They would probably be separate apps (eg. GNOME Photos vs [Entangle](https://entangle-photo.org/)), and we could label the second case `Photos wants to access your photo library on camera 12341234` (or "captured photos" or "storage" or "photos storage").

**Comment by matthiasclasen** [comment]
We have a camera portal now.

**Comment by muelli** [comment]
Will there be some documentation on [that page](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html)?

**Comment by dustymabe** [comment]
> We have a camera portal now.

Cross linking the PR that I think implemented this: https://github.com/flatpak/xdg-desktop-portal/pull/331

**Comment by matthiasclasen** [comment]
A sortof demo app is growing here: https://gitlab.gnome.org/matthiasc/video-play
