### ISSUE TITLE
/portal/camera/lockdown test fails

### ISSUE THREAD

**Issue by heftig** [flatpak/xdg-desktop-portal#394]
After upgrading from 1.5.1 to 1.5.2 and libportal 0.0.2, the new `/portal/camera/lockdown` test fails:

```
ERROR: test-portals - Bail out! xdg-desktop-portal:ERROR:tests/camera.c:72:camera_cb: 'ret' should be FALSE
```

[test-suite.log](https://github.com/flatpak/xdg-desktop-portal/files/3785812/test-suite.log)

I suspect this is because the tests do not wait for the lockdown portal to process the `Set`s for the `disable-*` properties. Adding `sleep (1)` after those calls let the testsuite progress further.

**Comment by matthiasclasen** [comment]
Yeah, many of these things are racy. We'll have to wait for a signal from the portal

**Comment by matthiasclasen** [comment]
That being said, the tests pass both locally and in ci.

**Comment by smcv** [comment]
I'm encountering the same problem while packaging this for Debian: all the lockdown tests *sometimes* fail, but not consistently.

I think it might be sufficient to do the property set via a `_sync` D-Bus call instead of the generated GObject property setters - I'm testing a patch that does that. To be fully confident that it's a solution I'd have to draw a sequence diagram, though.
