### ISSUE TITLE
Read-only pictures: how to use the screenshot portal?

### ISSUE THREAD

**Issue by maoschanz** [flatpak/xdg-desktop-portal#516]
I'm trying to use the screenshot portal to then edit the image

Here the method called to trigger a screenshot:
```python3
	def on_screenshot(self, *args):
		win = self.props.active_window

		gio_dbus_connection = Gio.bus_get_sync(Gio.BusType.SESSION, None)
		proxy = Gio.DBusProxy.new_sync(
			gio_dbus_connection,
			Gio.DBusProxyFlags.NONE, None,
			'org.freedesktop.portal.Desktop',
			'/org/freedesktop/portal/desktop',
			'org.freedesktop.portal.Screenshot',
			None
		)

		parent_window_id = ""
		args = GLib.Variant('(sa{sv})', (parent_window_id, {
			'interactive': GLib.Variant.new_boolean(True),
			'modal': GLib.Variant.new_boolean(False)
		}))

		try:
			result_GVariant = proxy.call_sync('Screenshot', args, \
			                         Gio.DBusCallFlags.NO_AUTO_START, 500, None)
			if result_GVariant is None:
				raise Exception("The DBus proxy didn't return an object path." \
				                 + "\nThe portal can't suscribe to the signal.")

			response_id = gio_dbus_connection.signal_subscribe(
				'org.freedesktop.portal.Desktop',
				'org.freedesktop.portal.Request',
				'Response',
				result_GVariant[0],
				None,
				Gio.DBusSignalFlags.NO_MATCH_RULE,
				self.receive_screenshot,
				None
			)
		except Exception as e:
			print(e)
```

Then i receive the answer from the portal:

```python3
	def receive_screenshot(self, *args):
		win = self.props.active_window
		win.present()

		# XXX Example of what args contains:
		# <Gio.DBusConnection object at 0x7f6106b64e60 (GDBusConnection at 0x557bc1767380)>,
		# ':1.49',
		# '/org/freedesktop/portal/desktop/request/1_2813/t/1811915328',
		# 'org.freedesktop.portal.Request',
		# 'Response',
		# GLib.Variant('(ua{sv})', (
		# 	0,
		# 	{'uri': <'file:///run/user/1000/doc/ca018260/Screenshot-7.png'>}
		# )),
		# None
		screenshot_state = args[5][0] # == 0 if success
		if screenshot_state == 1:
			# Action cancelled by the user
			return
		if screenshot_state == 2:
			win.prompt_message(True, _("Screenshot failed"))
			return

		weird_uri = args[5][1]['uri']
		f = Gio.File.new_for_uri(weird_uri)

		if f is not None:
			win.edit_file_in_new_tab(f)
```

The file is displayed in my editor, which is what i expect. But when the user wants to save their modifications, here is my issue:

```
g-file-error-quark: Failed to open “/run/user/1000/doc/25e111af/Screenshot-9.png” for writing: Permission denied (2)
```

Which would make the portal useless... are the files really read-only or did i miss something important?

**Comment by maoschanz** [comment]
Should i open this issue elsewhere or should i give up on doing anything useful with this portal?

**Comment by smcv** [comment]
> If it's not writable, the screenshots can't be edited by the app, so what would be the point, for the app, of taking them in the first place?

Your application gets the screenshot, as a sequence of bytes. It's entirely up to your application what it wants to do with those bytes. If you want them to end up in a file that you can edit in place, then you can:

* get the temporary, read-only path from the portal
* load that file into memory
* apply whatever edits or filters you want
* save them in a writeable location of your choice, either temporary or permanent

or:

* get the temporary, read-only path from the portal
* copy the file from that path to a writeable location of your choice, either temporary or permanent
* edit the writeable copy in-place

As an implementation detail of the way the portal has been designed, the bytes are transferred to you by writing them to a temporary file (which is read-only from your application's point of view), and telling your application which file it can read to get them. This does not mean that all your interactions with the screenshot, forever, have to go via that filename! It's just a convenient and reasonably efficient way to deliver the bytes to you without having to send them over D-Bus.

If a different API had been chosen - for example if the bytes had been transferred to your application as a very large D-Bus message, or in a sealed `memfd` attached to a D-Bus message - then you would still not be able to edit the screenshot in-place. You would still have to either edit it in-memory, or save a copy in a long-term location of your choice, and edit that copy.

For your use-case where the screenshot is opened for editing in a new tab, the best user-experience would probably be for the new tab to load the bytes of the screenshot, but treat it as a new untitled document instead of remembering the filename from which it loaded the bytes, so that when the user saves it, they are made to choose a new filename (similar to what happens when you use File->New..., File->Create->From Clipboard or File->Create->Screenshot... in GIMP).

**Comment by maoschanz** [comment]
>the best user-experience would probably be

Your suggestion is the 2nd one i listed: telling the user to access the file with the file-chooser portal. And as i wrote, it comes with UX issues that make the portal the least usable way to achieve this feature.

The best UX would be that, when the user press "save", the screenshot is saved at its existing path. No duplication, no file chooser: the file already exists, it has been created from the app and for the app, so the app should be able to access it, and i can't imagine why it should be read-only.

>in GIMP

the famous UX of GIMP is not my model

>the bytes are transferred to you by writing them to a **temporary file**

While developing/testing the code i posted here, i filled my XDG_PICTURES_DIR folder with dozens and dozens of files, and i can assure you they're not temporary at all... 

Are these files in ~/Pictures something the various implementations create on their own?

**Comment by hadess** [comment]
If you're going to take that tone, you can search the source code for details on the implementation yourself. I'm done trying to help you out.

**Comment by matthiasclasen** [comment]
> Which would make the portal useless... are the files really read-only or did i miss something important?

I'm not sure I agree on `useless`.

It is just an implementation detail that you have to be aware of. You can of course manipulate the image in whatever way you
want. You just can't save it to the same file that its been delivered in, but have to pick another location, probably in your apps writable area.
