### ISSUE TITLE
Implement 'lpr' command in terms of Print portal

### ISSUE THREAD

**Issue by wjt** [flatpak/xdg-desktop-portal#522]
Tuxpaint uses the `lpr` command to print; as a result, printing does not work. https://github.com/flathub/org.tuxpaint.Tuxpaint/issues/3

I did a quick hack to implement the `lpr` command in terms of the Print portal. It basically works!

https://github.com/flathub/org.tuxpaint.Tuxpaint/pull/9/commits/93ffacdac6dc7d13bfff08d6b8fdb2948a7347d4

It would be nice to redo that implementation in C, flesh out some of its rough edges, and ship it somewhere (libportal? flatpak-xdg-utils?) that other applications can use too.

**Comment by wjt** [comment]
(A number of apps on Flathub compile CUPS' implementation of lpr and then use `--socket=cups`; in principle these could use something like this instead.)

**Comment by Erick555** [comment]
I couldn't find other apps except okular that bundle lpr but qt doesn't support print portal so a portal wrapper isn't solution for them.

**Comment by hadess** [comment]
We could probably create a separate module under the flatpak project, as `flatpak-lpr`, just like we did for the `flatpak-xdg-utils`. If nobody minds I can create the module for you to push to.

**Comment by hadess** [comment]
> I couldn't find other apps except okular that bundle lpr but qt doesn't support print portal so a portal wrapper isn't solution for them.

Scribus needs it too: https://github.com/flathub/net.scribus.Scribus/issues/20
and Qt apps can use the gtk-based portals on GNOME, then printing is just broken for those Qt apps on KDE ;)

**Comment by Erick555** [comment]
> Scribus needs it too: flathub/net.scribus.Scribus#20

I saw it but read that there are handful of apps that bundle lpr already and couldn't find them on [github](https://github.com/search?q=org%3Aflathub+lpr&type=Code)

> and Qt apps can use the gtk-based portals on GNOME, then printing is just broken for those Qt apps on KDE ;)

How printing on kde would work when you replace `lpr` with lpr wrapper though? I hope the the result of what is proposed here doesn't mean qt apps on KDE lose printing capability which they just recently gained.

**Comment by wjt** [comment]
> We could probably create a separate module under the flatpak project, as `flatpak-lpr`, just like we did for the `flatpak-xdg-utils`. If nobody minds I can create the module for you to push to.

That could work.

I feel like step 1 is to write the non-toy implementation and ship it in Tuxpaint. I should probably have written "RFC" in the subject. 



> > Scribus needs it too: [flathub/net.scribus.Scribus#20](https://github.com/flathub/net.scribus.Scribus/issues/20)
> 
> I saw it but read that there are handful of apps that bundle lpr already and couldn't find them on [github](https://github.com/search?q=org%3Aflathub+lpr&type=Code)
> 
> > and Qt apps can use the gtk-based portals on GNOME, then printing is just broken for those Qt apps on KDE ;)
> 
> How printing on kde would work when you replace `lpr` with lpr wrapper though?

I don't intend 

 I hope the the result of what is proposed here doesn't mean qt apps on KDE lose printing capability which they just recently gained. In gnome it should work anyway.
> 
> EDIT: to clarify, printing in qt apps works right now with just `--socket=cups` or `--socket=cups` and `lpr` (vanilla version). They don't need special wrapper for that.

They don't need a special wrapper, but they do need a sandbox hole.

If KDE doesn't implement the print portal then indeed an application which switched from sandbox hole for cups + real `lpr` to this portal based `lpr` would break on KDE. The (necessary anyway!) fix for that would be to implement the print portal.

This is all

**Comment by Erick555** [comment]
> If KDE doesn't implement the print portal then indeed an application which switched from sandbox hole for cups + real lpr to this portal based lpr would break on KDE. The (necessary anyway!) fix for that would be to implement the print portal.

Print portal in Qt was considered unachievable in foreseeable future (AFAIK no upstream interest for that), that's why `--socket=cups` was added in flatpak 1.6. Considering that all apps that use `--socket=cups` use qt and lpr is bundled in okular (also qt app) then I don't see why you want to implement generic solution that is known working for single app and may break the others. Bundling this wrapper in that particular app shouldn't hurt.

**Comment by wjt** [comment]
Of course I'm not proposing breaking working apps!

I am suggesting including a portal-backed `lpr` in the runtime so that the non-zero set of apps & host systems which currently can't print but which could with such a command could do so. Apps which might choose to do something different, as in the helpful & informative examples you have given to explain why they are the way they are, would not need to do anything different and would continue to work as they are..
But never mind then.

**Comment by Erick555** [comment]
The problem is you can't name those apps beside one. For apps you aimed for writing:

> (A number of apps on Flathub compile CUPS' implementation of lpr and then use --socket=cups; in principle these could use something like this instead.) 

your proposal doesn't apply. One app (or even three) is rather too low number to ask even for a shared-module and you want add it to runtime! I would advice to find more affected apps, try your wrapper on them then submit proposal for general solution that makes maintenance of dozen apps simpler (without hurting others). In that order. Note that any runtime solution may be delayed for a couple of months at least so you will need to keep bundled fixes for them for a while anyway.

Another thing is that adding fake `lpr` in runtime would make it harder for apps that need real one to discover what's going wrong as there won't be `lpr: Command not found"` message anymore.
