### ISSUE TITLE
Portal for capturing audio from an application

### ISSUE THREAD

**Issue by euthane** [flatpak/xdg-desktop-portal#543]
I propose a portal where an application can request a copy of another application's audio stream without affecting its output to the speaker or any output device. This can be a nice supplement to the ScreenCast portal by also providing the audio output of the application. This can probably be done by communicating with PipeWire's session manager.

This is very niche. But this can be a great feature to video conferencing although there are no webapis for this (yet). Discord has this feature in Windows 10 though I haven't seen any documentation for this and a [forum thread](https://social.msdn.microsoft.com/Forums/en-US/86b605b2-17d3-4576-9570-a16bc8a710cf/hook-audio-buffers-of-windows-application-individually?forum=windowspro-audiodevelopment) confirms that discord is using undocumented windows api and they're not willing to give information about how they do it. So I can't give any working examples of this feature.

This is also great for screen recording programs like OBS to have access to an application's audio stream in an easy way.

**Comment by Conan-Kudo** [comment]
Zoom also is doing this by some tricky means with PulseAudio API on Linux, and it'd be nice to have this added as part of the screencast API so that applications can just do this without weird tricks.

**Comment by orowith2os** [comment]
Related: https://github.com/flatpak/xdg-desktop-portal/issues/957

**Comment by GeorgesStavracas** [comment]
These are two different requests: one for the Screencast portal to potentially provide the window's audio stream in addition to the captured frames; the other is for a (theoretical as of now) Audio portal to expose apps' audio streams.

The former has had more discussions in #957, so I think I'm going to close this issue as duplicated instead of that one.

The latter is being discussed at https://github.com/flatpak/xdg-desktop-portal/discussions/1142

Thanks for the proposal, let's move these discussions to the appropriate places
