### ISSUE TITLE
Portal doesn't throttle URL handler dialogues

### ISSUE THREAD

**Issue by Latesil** [flatpak/xdg-desktop-portal#556]
Every time when I open Style Editor on reddit site, Firefox opens a tons of system messages in separate window, which tells me about system handlers.

Fedora 33, X11
GNOME 3.38.2
Flatpak 1.8.4

How to reproduce:
1. Go to https://www.reddit.com
2. Open Style Editor in Developer Tools

(sorry if it is wrong place to report)

**Comment by hadess** [comment]
That looks like a problem with Firefox, not Flatpak or xdg-desktop-portal. It might be that the extension (or Firefox) expects those URLs to be handled internally but using an external codepath (eg. it only works well outside of the sandbox because you don't have any dialogues in the middle of the transaction).

Would be good to avoid showing tons of dialogues for a single app though.
