### ISSUE TITLE
xdg-desktop-portal-gtk and xdg-desktop-portal-wlr coexistence

### ISSUE THREAD

**Issue by rumpelsepp** [flatpak/xdg-desktop-portal#619]
xdg-desktop-portal-gtk and xdg-desktop-portal-wlr seem to have problems when both are needed at the same time. I use sway and -wlr is required for screensharing, while -gtk is required for open/save dialogues of flatpak applications. In fact, once -gtk is started, screensharing doesn't work anymore and the following error ist logged:

```
Aug 18 15:55:26 kronos xdg-desktop-por[269222]: A backend call failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.impl.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop
Aug 18 15:55:26 kronos xdg-desktop-por[269222]: Failed to close session implementation: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.impl.portal.Session” on object at path /org/freedesktop/porta>
```

Killing -gtk and clicking the screensharing button in, e.g., firefox again spawns -wlr and screensharing works. @emersion confirmed in IRC that both portals should be able to coexist. I use Arch Linux and the distro provided packages.

**Comment by tinywrkb** [comment]
This is due to Gnome Desktop specific portals implementations in `xdg-desktop-portal-gtk`.  
You need to export `XDG_CURRENT_DESKTOP="sway"` in your user environment, and also in the environment of `xdg-desktop-portal.service`, which you can do with a systemd user override (systemctl --user edit ...).

You can also wait for the next major release of Gnome which going to have the Gnome portals implementations in `xdg-desktop-portal-gnome`, see [this](https://gitlab.gnome.org/GNOME/gnome-build-meta/-/merge_requests/1176), and then those will be disabled in `xdg-desktop-portal-gtk`.

Another option is to build `xdg-desktop-portal-gtk` without the Gnome portals, see an example [here](https://github.com/tinywrkb/pkgbuilds/blob/main/xdg-desktop-portal-gtk-gnomefree/PKGBUILD).

**Comment by rumpelsepp** [comment]
Thank you very much for your explanation! I had set the variable `XDG_CURRENT_DESKTOP=sway` but the missing piece was `systemctl --user import-environment XDG_CURRENT_DESKTOP`. Now the portals start correctly.
