### ISSUE TITLE
Support explicit priority/fallback if multiple backends installed

### ISSUE THREAD

**Issue by vchernin** [flatpak/xdg-desktop-portal#656]
xdg-desktop-portal should support properly handling multiple backends installed, with a more robust priority/fallback system.

It is considered acceptable to have multiple backends installed. For example, KDE users may want xdg-desktop-portal-kde and xdg-desktop-portal-gtk installed, since -gtk provides the settings and appchooser portal used by GTK apps.

However, the portal used is based on lexicographic order. This means if say -wlr and -gtk are installed, -gtk would be prioritized. Same with -kde and -gtk. Note if the current desktop environment sets `XDG_CURRENT_DESKTOP`, -kde or -wlr should be preferred correctly (see https://github.com/flatpak/xdg-desktop-portal-gtk/pull/362#issuecomment-966267403).

This is problematic since the portals provided by the "secondary" backend (e.g. -gtk on a kde desktop), could be used instead of the "primary" backend (eg -kde on a kde desktop).

How could this be defined? Should xdg-desktop-portal hard code priorities between different backends? Should individual backends communicate to xdg-desktop-portal they should be "primary"?

Originally discussed in https://github.com/flatpak/xdg-desktop-portal-gtk/pull/362

**Comment by nanonyme** [comment]
One possibility would be DE would declare preferred backends in preferred order somehow (environment variable?). Would that be good enough? Are there cases where priority is not trivial to define?

**Comment by nanonyme** [comment]
Also, what should be done if none of the backends in list match but something not in list would?

**Comment by smcv** [comment]
The backend to use is chosen on a per-interface basis, so it is OK to split functionality between backends. For example, it's fine to choose `foo.portal` for `o.fd.impl.portal.One` and `bar.portal` for `o.fd.impl.portal.Two`.

GNOME is a concrete example of this: GNOME-appropriate behaviour for various interfaces is distributed between x-d-p-gnome (`gnome.portal`), x-d-p-gtk (`gtk.portal`), gnome-shell (`gnome-shell.portal`) and gnome-keyring (`gnome-keyring.portal`).

The current priority/fallback behaviour is:

* First, x-d-p enumerates all portals whose `.portal` file declares that they are suitable for the `$XDG_CURRENT_DESKTOP` via the `UseIn` field.
* If this results in only finding one implementation of an interface, it is used, and we stop here: for example, in a GNOME environment, the only implementation of `o.fd.impl.portal.Secret` is `gnome-keyring.portal`.
* If this results in finding more than one implementation of an interface, the first one in lexicographic order is used, and we stop here. This happens to do the right thing for `x-d-p-gtk` vs. `x-d-p-gnome`, because `gnome` happens to sort lexicographically lower than `gtk`, but that's more like a lucky accident than by design.
* If this results in finding *no* implementations of an interface, then the fallback is to ignore the `UseIn` field, and enumerate all portals indiscriminately. Again, the first one in lexicographic order is used.
* If there are still no portals found, then x-d-p does not implement the interface.

This is not ideal. Ideally, we would be able to distinguish between:

* implementations that *can be* used from any desktop environment, but are less ideal in some desktop environments
    * for example, a GTK `FileChooser` is primarily for use with GTK-based desktops like GNOME, MATE, Cinnamon, LXDE and XFCE; it will look out-of-place in a Qt-based desktop, so ideally in a Qt-based desktop like LXQT, we would use something provided by the desktop instead; but it will still *work* fine in any desktop environment, so it's always better than nothing, and we can safely use it as a fallback
* implementations that can only function on some desktop environments, and will fail on others
    * for example, when x-d-p-gtk implements `o.fd.impl.portal.ScreenCast`, it is relying on mutter APIs, so it can work on GNOME Shell and on Budgie, but will not work at all on (for example) Mate, Cinnamon, GNOME Flashback, LXDE or XFCE

**Comment by smcv** [comment]
> One possibility would be DE would declare preferred backends in preferred order somehow (environment variable? this would be trivial for user to set and override as well).

An environment variable is not at all trivial to set and override, particularly for user-services. We should not create new environment variables as a primary way to communicate anything down to x-d-p - it's OK for them to be used for development and debugging, but the overall system should be designed such that it can "do the right thing" without introducing new x-d-p-specific environment variables.

There are about a dozen different ways to set environment variables. Some of them only work for systemd users, some of them only work for specific PAM configurations, some of them don't work for systemd user services and/or D-Bus session services, some of them *only* work for systemd user services and/or D-Bus session services, some of them are distro-specific, some of them only work for X11 users, some of them only work for gdm users, some of them only work for users whose configured interactive shell is bash. It's a mess, and we should try not to make it worse.

**Comment by apiraino** [comment]
I'll chime in this issue which seems relevant also to me. I use Sway and have installed `xdg-desktop-portal-wlr==0.5.0-1` in my Debian system, mainly to be able to use the screensharing capability provided by the Pipewire implementation of the portal `org.freedesktop.impl.portal.ScreenCast (still confused about these names).

I also have installed `xdg-desktop-portal-gtk==1.10.0-1` and after some digging I've discovered that there's a conflict when choosing the ScreenCast portal. I have `XDG_CURRENT_DESKTOP=sway` and these are my configuration files:

```
$ cat /usr/share/xdg-desktop-portal/portals/wlr.portal 
[portal]
DBusName=org.freedesktop.impl.portal.desktop.wlr
Interfaces=org.freedesktop.impl.portal.Screenshot;org.freedesktop.impl.portal.ScreenCast;
UseIn=wlroots;sway;Wayfire;river

###
### Notice: org.freedesktop.impl.portal.ScreenCast has been removed because conflicting
###
$ cat /usr/share/xdg-desktop-portal/portals/gtk.portal 
[portal]
DBusName=org.freedesktop.impl.portal.desktop.gtk
Interfaces=org.freedesktop.impl.portal.FileChooser;org.freedesktop.impl.portal.AppChooser;org.freedesktop.impl.portal.Print;
org.freedesktop.impl.portal.Screenshot;org.freedesktop.impl.portal.Notification;org.freedesktop.impl.portal.Inhibit;
org.freedesktop.impl.portal.Access;org.freedesktop.impl.portal.Account;org.freedesktop.impl.portal.Email;
org.freedesktop.impl.portal.RemoteDesktop;org.freedesktop.impl.portal.Lockdown;org.freedesktop.impl.portal.Background;
org.freedesktop.impl.portal.Settings;org.freedesktop.impl.portal.Wallpaper;
UseIn=gnome
```

According to [this](https://github.com/flatpak/xdg-desktop-portal/issues/656#issuecomment-966276573) and [this](https://github.com/flatpak/xdg-desktop-portal-gtk/pull/362#issuecomment-966267403) comments, the wl-roots portal should be automatically selected, but it doesn't look to be the case.

My workaround is to manually remove `org.freedesktop.impl.portal.ScreenCast` from the list of portals in `/usr/share/xdg-desktop-portal/portals/gtk.portal` so the other correct ScreenCast will be choosen.

I'm still figuring things out so I'm not sure if there is a bug and where.

I'd be happy to receive a feedback about this.

Thanks!

**Comment by smcv** [comment]
I think @apiraino's use case with sway is something that is already meant to work, so this feature request shouldn't be necessary to resolve that. It looks like a bug: if `XDG_CURRENT_DESKTOP=sway`, then the portal with `UseIn=...;sway;...` should automatically be preferred over the one without.

One possible reason why that might not work is if the `XDG_CURRENT_DESKTOP` environment variable is set in GUI processes, but not in the `dbus-daemon --session` activation environment and/or the `systemd --user` activation environment. The environment variables that matter are the ones inherited by the `xdg-desktop-portal` process.

**Comment by hadess** [comment]
> One possible reason why that might not work is if the `XDG_CURRENT_DESKTOP` environment variable is set in GUI processes, but not in the `dbus-daemon --session` activation environment and/or the `systemd --user` activation environment. The environment variables that matter are the ones inherited by the `xdg-desktop-portal` process.

This might be relevant: https://github.com/flatpak/xdg-desktop-portal/issues/285#issuecomment-719076010

**Comment by smcv** [comment]
> > The environment variables that matter are the ones inherited by the `xdg-desktop-portal` process.
> 
> This might be relevant: [#285 (comment)](https://github.com/flatpak/xdg-desktop-portal/issues/285#issuecomment-719076010)

Yes, that situation is similar to the one I suspected. The linked comment is about `DISPLAY` and I was talking about `XDG_CURRENT_DESKTOP`, but the requirements for both variables are the same: they need to be made available to the `dbus-daemon --session`, and to `systemd --user` if used.

**Comment by apiraino** [comment]
After [applying my workaround](https://github.com/flatpak/xdg-desktop-portal/issues/656#issuecomment-975954843) I cannot reproduce the issue anymore, but wanted to expand on @smcv's comment on how to make available the needed env variables. 
On the [xdg-desktop-portal-wlr wiki](https://github.com/emersion/xdg-desktop-portal-wlr/wiki/systemd-user-services,-pam,-and-environment-variables#so-how-should-i-set-this-environment-variable) it is mentioned how to do that:

If using systemd: `systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP`
else: `dbus-update-activation-environment --all`

(can't test them now because I cannot go back to a setup where `org.freedesktop.impl.portal.ScreenCast` is not correctly picked up...).

**Comment by redtide** [comment]
> One possible reason why that might not work is if the `XDG_CURRENT_DESKTOP` environment variable is set in GUI processes, but not in the `dbus-daemon --session` activation environment and/or the `systemd --user` activation environment. The environment variables that matter are the ones inherited by the `xdg-desktop-portal` process.

I'm not much an expert in this context but what about `XDG_SESSION_DESKTOP` instead?

**Comment by dancojocaru2000** [comment]
Another usecase is [darkman](https://gitlab.com/WhyNotHugo/darkman), a software that provides an implementation for the color-scheme setting and automatically switches it at sunrise and sunset. 

For now the alphabetic order works since `d` is less than any other implementation I have, but other such usecases might not have a name starting with `d`, so it would be nice if I could say that for `org.freedesktop.portal.Settings` then `org.freedesktop.appearance`, darkman is who I want to provide the backend.

**Comment by jim3692** [comment]
I solved the issue in Hyprland by running this on startup.

`bash -c 'export XDG_CURRENT_DESKTOP=sway ; systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP ; dbus-update-activation-environment --all ; systemctl --user restart xdg-desktop-portal'`

**Comment by spikespaz** [comment]
> I solved the issue in Hyprland by running this on startup.
> 
> `bash -c 'export XDG_CURRENT_DESKTOP=sway ; systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP ; dbus-update-activation-environment --all ; systemctl --user restart xdg-desktop-portal'`

Where did you use this, and with what portals on your system?

**Comment by jim3692** [comment]
> > I solved the issue in Hyprland by running this on startup.
> > `bash -c 'export XDG_CURRENT_DESKTOP=sway ; systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP ; dbus-update-activation-environment --all ; systemctl --user restart xdg-desktop-portal'`
> 
> Where did you use this, and with what portals on your system?

I added this line to my `hyprland.conf`
```
exec-once=bash -c 'export XDG_CURRENT_DESKTOP=sway ; systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP ; dbus-update-activation-environment --all ; systemctl --user restart xdg-desktop-portal'
```

The portals that are installed on my system are:
- xdg-desktop-portal-gtk
- xdg-desktop-portal-kde
- xdg-desktop-portal-wlr

I only need the wlr portal, but I installed the others just to test it. Without this line, I had the portal trying to connect to kde and eventually failing due to a timeout. This happens because my version of `/usr/share/xdg-desktop-portal/portals/wlr.portal` does not include Hyprland in its `UseIn` section.

**Comment by spikespaz** [comment]
> > > I solved the issue in Hyprland by running this on startup.
> > > `bash -c 'export XDG_CURRENT_DESKTOP=sway ; systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP ; dbus-update-activation-environment --all ; systemctl --user restart xdg-desktop-portal'`
> > 
> > Where did you use this, and with what portals on your system?
> 
> @spikespaz I added this line to my `hyprland.conf`
> 
> ```
> exec-once=bash -c 'export XDG_CURRENT_DESKTOP=sway ; systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP ; dbus-update-activation-environment --all ; systemctl --user restart xdg-desktop-portal'
> ```
> 
> The portals that are installed on my system are:
> - xdg-desktop-portal-gtk
> - xdg-desktop-portal-kde
> - xdg-desktop-portal-wlr
> 
> I only need the wlr portal, but I installed the others just to test it. Without this line, I had the portal trying to connect to kde and eventually failing due to a timeout. This happens because my version of `/usr/share/xdg-desktop-portal/portals/wlr.portal` does not include Hyprland in its `UseIn` section.

As far as I'm aware, the only difference from yours to mine is changing the `XDG_CURRENT_DESKTOP` to `sway`, which *seems* like a bad idea. I have left the global envvar alone and tried to wrap the portal executable to lie and say I'm `sway`. That worked partially, but the KDE portal failed to respect QT5CT/Kvantum, and Firefox didn't recognize my dconf for dark mode. Not sure what other problems I'm likely to run into if session variables are wrongly reporting the window manager.

Perhaps setting the variable isn't enough and exporting the session with the rest of the commands necessary is truly required. Some input from an expert would be nice here.

**Comment by redtide** [comment]
> but the KDE portal failed to respect QT5CT/Kvantum, and Firefox didn't recognize my dconf for dark mode.

IDK if relevant and sorry for the OT, but I had (and I recall also other people too) problems when using qt5ct, it messed up my themes and in my LXQt system even the file requester. OTOH I use Kvantum with no problems.

**Comment by spikespaz** [comment]
> > but the KDE portal failed to respect QT5CT/Kvantum, and Firefox didn't recognize my dconf for dark mode.
> 
> IDK if relevant and sorry for the OT, but I had (and I recall also other people too) problems when using qt5ct, it messed up my themes and in my LXQt system even the file requester. OTOH I use Kvantum with no problems.

In my experience Kvantum does not work well without QT5CT. How do you use it standalone, and properly? I tried setting environment variables that came up with a Google search but it was unlikely to work in most applications, especially KDE ones.
