### ISSUE TITLE
Should filename responses be encoded?

### ISSUE THREAD

**Issue by falkTX** [flatpak/xdg-desktop-portal#799]
Hi, I have implemented desktop-portal in my application as a way to get native desktop file browsers.
I am facing an issue of inconsistent behaviour, and need some guidance.

gtk portal encodes filenames with spaces as %20, for example:
```
signal time=1652636523.412908 sender=:1.162 -> destination=:1.212 serial=209 path=/org/freedesktop/portal/desktop/request/1_212/t; interface=org.freedesktop.portal.Request; member=Response
   uint32 0
   array [
      dict entry(
         string "choices"
         variant             array [
            ]
      )
      dict entry(
         string "uris"
         variant             array [
               string "file:///home/user/Downloads/Drumkits/0_FOREIGN_TECK/Foreign%20Teck%20-%20Dream%20to%20Reality%20Drum%20Kit/808/BagOnMe%20(808).wav"
            ]
      )
   ]
```

kde portal though leaves the spaces as is:
```
signal time=1652637257.895877 sender=:1.44 -> destination=:1.1164 serial=1060 path=/org/freedesktop/portal/desktop/request/1_1164/t; interface=org.freedesktop.portal.Request; member=Response
   uint32 0
   array [
      dict entry(
         string "uris"
         variant             array [
               string "file:///home/falktx/with spaces.vcv"
            ]
      )
   ]
```

which one is correct? how to proceed?

did this perhaps change in the spec in between versions? if not, I am not sure how to go about it, as always decoding will lead to errors if a filename purposefully has "%20" in its name.

**Comment by smcv** [comment]
They're `file:` URIs, not filenames. If you want a filename, it's always necessary to decode them (replace `%xx` escape sequences with the escaped byte) during conversion from URI to filename.

If a file has `%` in its filename, then its representation as a `file:` URI needs to have `%25` instead, the same as for any other use of URIs.

It seems like a bug in xdg-desktop-portal-kde if it doesn't encode spaces as `%20`, because the [URI specification](https://datatracker.ietf.org/doc/html/rfc3986) doesn't allow unencoded spaces. However, the [WHATWG URL specification](https://url.spec.whatwg.org/) defines an interpretation for various URIs/URLs that are formally invalid, including `file:///home/falktx/with spaces.vcv`, which would normalize to `file:///home/falktx/with%20spaces.vcv`.

**Comment by falkTX** [comment]
Interesting. So KDE behaviour is slightly wrong.
I just did a test with a filename that has a literal %20 on its name, the result is:
```
signal time=1652658011.454240 sender=:1.44 -> destination=:1.1189 serial=1121 path=/org/freedesktop/portal/desktop/request/1_1189/t; interface=org.freedesktop.portal.Request; member=Response
   uint32 0
   array [
      dict entry(
         string "uris"
         variant             array [
               string "file:///home/falktx/Source/Cardinal/test file with %2520 in its name.vcv"
            ]
      )
   ]
```
So % gets converted to %25 by KDE, at least this will help with the conversion, so a literal %20 does not get converted to spaces by mistake.

**Comment by smcv** [comment]
I think perhaps the problem here is that the KDE portal is using `QUrl::toString(PrettyDecoded)` (which displays a URI in a semi-user-friendly way, similar to what appears in web browsers' address bars) where I would have expected `QUrl::toString(FullyEncoded)` to produce a more appropriate output (one that can be parsed successfully with `QUrl::StrictMode`, which the "pretty" string cannot).

As long as it's at least minimally in URI encoding, such that decoding will produce the right thing, it should be OK either way. Consumers of these `file:` URIs should be using something like GLib's `g_file_new_for_uri()` and `g_file_get_path()`, Python's `urllib.parse.urlparse` and `urllib.parse.unquote`, or Qt's `QUrl::QUrl(const QString &)` and `QUrl::toLocalFile()`.

**Comment by falkTX** [comment]
Interesting, thanks for the deep dive.
I do not have access to those in my application (and adding such big dependency just for a quick string decoder seems a bit too much) so I guess I will roll my own decoder, shouldnt be too hard

**Comment by Be-ing** [comment]
[Bug report on KDE's tracker](https://bugs.kde.org/show_bug.cgi?id=454850)

**Comment by nicolasfella** [comment]
Should be fixed with https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/merge_requests/108

For issues like this reports to https://bugs.kde.org/enter_bug.cgi?product=xdg-desktop-portal-kde are appreciated

**Comment by GeorgesStavracas** [comment]
Thanks for fixing this on KDE. Closing this one as resolved.
