### ISSUE TITLE
Only allow NetworkMonitor calls if the peer has network access

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/xdg-desktop-portal#81]
This should be easy to check now that we use the peer /.flatpak-info file to identify the peer app. This file contains the network access info.

**Comment by matthiasclasen** [comment]
We already do that, see https://git.gnome.org/browse/glib/tree/gio/gportalsupport.c#n51

**Comment by jhenstridge** [comment]
If I understand it, that code in GIO represents the application inside the sandbox choosing not to use the portal.  That's quite different from the portal deciding whether or not to respond to a sandboxed application.

Unless the sandbox is restricting access to the NetworkMonitor interface in the case of no-network apps, then the portal should be protecting itself.

**Comment by matthiasclasen** [comment]
You are right. It makes sense to do this on the portal side, certainly.

**Comment by matthiasclasen** [comment]
I've pushed a branch https://github.com/matthiasclasen/xdg-desktop-portal/tree/network-lockdown that does this for the proxy portal. Unfortunately, doing the same for the network monitor portal (with its current API) is hard or impossible, since it relies on properties, and the gdbus code is not able to do access control checks for properties. I can mark the properties as uncached, and I can override the get_properties vfunc in the interface skeleton, but I don't have access to the method invocation in get_properties, so I can't return different results based on whether the caller's sandbox has network access or not.

**Comment by matthiasclasen** [comment]
Only alternative I see is to move the network monitor portal to a different API, and avoid properties.

**Comment by matthiasclasen** [comment]
See https://github.com/flatpak/xdg-desktop-portal/pull/198
