### ISSUE TITLE
[Feature Request] Support for Private Windows

### ISSUE THREAD

**Issue by Obsessee** [flatpak/xdg-desktop-portal#824]
Inspired by the following post: https://gitlab.gnome.org/GNOME/mutter/-/issues/2186
Posted on the wayland-protocols gitlab as well: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/95

I'm looking for the possibility to tag specific surfaces with a "private" or "hidden" tag. This tag would prevent screencasting applications the ability to capture the app's graphics. This would be useful when the entire screen is being captured, and an application like a password manager gets opened, where a leak could be disastrous.

I'm unsure if wayland, xdp, or both would be the right place for this, considering that it would be preferred for apps to hint this themselves and also allow users the option to disable this.

I know Windows does this already in some way to prevent videos with DRM from being captured. It blocks the capturing and replaces it with a complete black screen.

Having the option in a xdp allows permission managers like Flatseal to allow users to set the "hidden" permission.

**Comment by smcv** [comment]
Wayland applications running under Flatpak (and I think also Snap) communicate directly with the Wayland compositor, so I think the main route for this information has to be directly from the application to the Wayland compositor, without going via x-d-p.

The x-d-p permission store might be a reasonable place to put an override for "if this app sets the hint to make its windows uncapturable, don't obey it", or conversely "this app is allowed to capture otherwise uncapturable windows".

I think this feature request is something that would have to be led by developers or contributors of the various Wayland compositors (GNOME Shell, KDE Plasma, the Sway family, etc.), with any code for it in x-d-p being secondary.

**Comment by GeorgesStavracas** [comment]
I'd go beyond what @smcv said, and I'll claim that this is entirely outside the realm of xdg-desktop-portal. x-d-p is not opinionated on what compositors do, nor how they capture their contents. Private surfaces would be entirely implemented by the compositor, and the portal backend, but not by x-d-p. Therefore, this feature is not actionable on this repository.
