### ISSUE TITLE
Error filling-up syslog: broker_posix.cc(46)] Received unexpected number of handles

### ISSUE THREAD

**Issue by gasp** [flatpak/xdg-desktop-portal#828]
[xdg-desktop-portal-going-crazy](https://user-images.githubusercontent.com/597067/176629281-eabf3bfc-1ff9-4a23-8b87-17c6b640539a.gif)

this error is filling-up `/var/log/syslog` really quickly (41G of logs generated in about two hours)
and this error isn't descriptive enough to help me fix 

how can I stop the bleed?

```
Jun 30 10:22:59 abia xdg-desktop-portal[16184]: [1320889:1:0100/000000.879907:ERROR:broker_posix.cc(46)] Received unexpected number of handles
Jun 30 10:22:59 abia xdg-desktop-portal[16184]: [1320889:1:0100/000000.879911:ERROR:command_buffer_proxy_impl.cc(96)] ContextResult::kFatalFailure: AllocateAndMapSharedMemory failed

```

**Comment by hadess** [comment]
xdg-desktop-portal is just posting this particular app's output. The error is from chrome/chromium, so you just need to stop using it to not see errors anymore.

**Comment by smcv** [comment]
Anything that is run by the portal as a subprocess, without using D-Bus activation, will get its output logged as though it was part of the portal's own output. This is not a portal bug, and the portal does not contain any code that matches `broker_posix.cc` or `command_buffer_proxy_impl.cc`.

I've opened https://gitlab.gnome.org/GNOME/glib/-/issues/2682 for the wrongly-attributed output. Solving that issue would result in the browser's output being logged as something like `google-chrome.desktop[12345]` rather than `xdg-desktop-portal[16184]`.

The error message `Received unexpected number of handles` seems to be what Chrome does when `/dev/shm` runs out of memory. Please contact your web browser's support channels or your OS distribution's support channels if you cannot solve this.
