### ISSUE TITLE
ScreenCast: handle resolution change properly

### ISSUE THREAD

**Issue by daniel-stm** [flatpak/xdg-desktop-portal#829]
The current situation seems to be that, on resolution change

- Gnome stops sending updates, with no indication of why that is
- Plasma continues providing updates, but they are broken. The buffer remains at the old size. If the new resolution is bigger, buffer still contains old data. If the new resolution is smaller, the buffer seems to contain somewhat reasonable data, but still useless as it doesn't match the the outdated resolution meta data.

Does the specification need to be clarified what should happen in this scenario, or is it safe to assume that implementations should just provide updates with buffers (and meta data) matching the new dimensions?
Or should some additional signaling take place?

**Comment by jadahl** [comment]
This should probably be something handled via PipeWire stream re-negotiation, not via the portal, since that is the place these things take place. For example, with virtual monitors, resizing can be done and uses stream re-negotiation, only that it happens in response to the client asking for it, not the user changing monitor settings via some monitor configuration application.

**Comment by GeorgesStavracas** [comment]
As @jadahl said, this should be handled via PipeWire. We already have examples of renegiating streams (e.g. the KDE implementation of the screencast portal). Please report both bugs, respectively, to [xdg-desktop-portal-gnome](https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/) and [xdg-desktop-portal-kde](https://bugs.kde.org/)
