### ISSUE TITLE
Add org.freedesktop.portal.Secret support for KDE

### ISSUE THREAD

**Issue by AsciiWolf** [flatpak/xdg-desktop-portal#970]
KWallet [supports](https://invent.kde.org/frameworks/kwallet/-/merge_requests/11) _org.freedesktop.secrets_ since 5.97. However, it looks like that [org.freedesktop.portal.Secret](https://github.com/flatpak/xdg-desktop-portal/blob/main/data/org.freedesktop.portal.Secret.xml) is GTK/GNOME-only at the moment. This prevents Flatpak applications using _org.freedesktop.secrets_ from being able to save credentials when running under KDE. See this ticket as an example: https://github.com/flathub/com.mojang.Minecraft/issues/116

**Comment by smcv** [comment]
xdg-desktop-portal doesn't talk directly to an `org.freedesktop.secrets` implementation. Instead, gnome-keyring provides the `org.freedesktop.impl.portal.Secret` interface, and xdg-desktop-portal talks to that.

I don't know the precise details of why it was done like this instead of `org.freedesktop.secrets`, but I suspect the reason it was done this way is so that gnome-keyring can show an appropriate prompt with details of the app that is making the request - `org.freedesktop.secrets` might not provide enough information to do that?

To make this work as well in KDE as it does in GNOME, either KWallet can implement `org.freedesktop.impl.portal.Secret` like gnome-keyring does (I suspect this is the preferred route because it will give KWallet more info about the requesting app), or xdg-desktop-portal-kde can implement `org.freedesktop.impl.portal.Secret` by talking to KWallet. Either of those should be a way to make this work in KDE without any code changes in this project.

**Comment by AsciiWolf** [comment]
Ah, interesting! I will file a KWallet ticket about adding the _org.freedesktop.impl.portal.Secret_ support. Thanks!

**Comment by smcv** [comment]
FYI the initial implementation in gnome-keyring was https://gitlab.gnome.org/GNOME/gnome-keyring/-/merge_requests/18. Don't look too closely at the exact implementation (there have been fixes after that point) but the "shape" of the implementation should be right. The key piece of plumbing is `daemon/gnome-keyring.portal`.

**Comment by AsciiWolf** [comment]
I have [reported it](https://bugs.kde.org/show_bug.cgi?id=466197) as an upstream KWallet issue. Thanks!

**Comment by nicolasfella** [comment]
https://invent.kde.org/frameworks/kwallet/-/merge_requests/67 implements the portal in KWallet

**Comment by Mailaender** [comment]
I added
```yaml
- --talk-name=org.freedesktop.secrets
- --talk-name=org.kde.kwalletd5
- --talk-name=org.kde.kwalletd6
```
to https://github.com/flathub/com.lablicate.OpenChrom and while it can find the secret service no passwords are persisted across application restarts.
