### ISSUE TITLE
Sometimes apps don't remember "last folder used"

### ISSUE THREAD

**Issue by BillDietrich** [flatpak/xdg-desktop-portal#992]
I've seen this in multiple apps, but the most prominent offender is Firefox.  When using Flatpak of the app, and portals, I have to keep navigating to the same folder over and over again if (for example) I want to save multiple images in the same folder.

Before you say this is an app bug, go file against the app, I've seen it in multiple apps and distros and DEs, which leads me to think perhaps the portal specification or guidance or API maybe is lacking in this area.  Is there a way for an app to remember and specify the last folder used ?  Is this advertised to app developers ?  Today the UX of using portals in some apps is a bad experience because of this issue.  What can be done to improve it ?  Thanks.

**Comment by ssokolow** [comment]
In Firefox's case, it's [issue 873](https://github.com/flatpak/xdg-desktop-portal/issues/973).

Basically, there's a bug in the portal where it'll translate user-visible paths not granted via manifest permissions (`flatpak override`/Flatseal) into documents portal paths when you click Ok, but won't then reverse the process when an application asks to have the dialog pre-open a specific folder rather than letting the portal remember the last-used location.

The workaround is to use manifest permissions to grant access to commonly used folders so there's no need to invoke the missing reverse translation.

**Comment by BillDietrich** [comment]
Also happens in Akregator's "Save Link As ...", other apps.

**Comment by lissyx** [comment]
@ebassi Could you please close this then ? Thanks !

**Comment by GeorgesStavracas** [comment]
Yup, should be fixed
